name: code_text_field
description: A customizable code field supporting syntax highlighting, bi-directionnal scrolling and code modifiers
version: 1.1.1
homepage: https://github.com/BertrandBev/code_field

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  linked_scroll_controller:
  highlight:
  flutter_highlight:
  runtime_flutter_code_highlighter:
    git:
      url: git@github.com:open-runtime/code_highlighter.git
      ref: init
      path: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
